apiVersion: v1
kind: DeploymentConfig
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: accounts
    spec:
      containers:
      - name: accounts
        image: weaveworksdemos/accounts
        command: ["java","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: accounts
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accounts-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accounts-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: accounts-db
  labels:
    name: accounts-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: accounts-db
    spec:
      volumes:
        -
          name: accounts-data
          persistentVolumeClaim:
            claimName: accounts-data
        -
          name: accounts-config
          persistentVolumeClaim:
            claimName: accounts-config
      containers:
      - name: accounts-db
        image: mongo
        volumeMounts:
        - name: accounts-data
          mountPath: /data/db
        - name: accounts-config
          mountPath: /data/configdb
        terminationMessagePath: /dev/termination-log
        ports:
        - name: mongo
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  labels:
    name: accounts-db
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: accounts-db
