apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cart
  labels:
    name: cart
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cart
    spec:
      containers:
      - name: cart
        image: weaveworksdemos/cart
        command: ["java","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    name: cart
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: cart
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cart-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cart-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cart-db
  labels:
    name: cart-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cart-db
    spec:
      volumes:
        -
          name: cart-data
          persistentVolumeClaim:
            claimName: cart-data
        -
          name: cart-config
          persistentVolumeClaim:
            claimName: cart-config
      containers:
      - name: cart-db
        image: mongo
        volumeMounts:
        - name: cart-data
          mountPath: /data/db
        - name: cart-config
          mountPath: /data/configdb
        ports:
        - name: mongo
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  labels:
    name: cart-db
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: cart-db
