apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login
  labels:
    name: login
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: login
    spec:
      containers:
      - name: login
        image: weaveworksdemos/login
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    name: login
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: login
