apiVersion: v1
kind: DeploymentConfig
metadata:
  name: orders
  labels:
    name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
      - name: orders
        image: weaveworksdemos/orders
        command: ["java","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=8080"]
        ports:
        - containerPort: 8080
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orders-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orders-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: orders
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      volumes:
        -
          name: orders-data
          persistentVolumeClaim:
            claimName: orders-data
        -
          name: orders-config
          persistentVolumeClaim:
            claimName: orders-config
      containers:
      - name: orders-db
        image: mongo
        volumeMounts:
        - name: orders-data
          mountPath: /data/db
        - name: orders-config
          mountPath: /data/configdb
        ports:
        - name: mongo
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: orders-db
