---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbit-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      volumes:
        -
          name: rabbit-data
          persistentVolumeClaim:
            claimName: rabbit-data
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        volumeMounts:
        - name: rabbit-data
          mountPath: /var/lib/rabbitmq
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    # the port that this service should serve on
  - port: 5672
    targetPort: 5672
  selector:
    name: rabbitmq
